### ISSUE TITLE
Delay activation of X-Raas after scenario load

### ISSUE THREAD

**Issue by jfjoubert** [skiselkov/X-RAAS2#1]
Hi Saso,

Would it be possible to have a couple of seconds delay after X-Plane has finished loading the plane and scenery? I always get multiple callouts even before the screen changed to the inside of the cockpit from the X-Plane loading menu... just thought that a slight delay might help.

Thanks,
Jean

**Comment by skiselkov** [comment]
There was already a delay in there, but it might not be enough. I'll extend it.

**Comment by jfjoubert** [comment]
Thanks Saso.

Let me know once implemented and I will test.

**Comment by skiselkov** [comment]
Implemented in `v2.1b3`, please test.

**Comment by jfjoubert** [comment]
Thanks... delay is spot on in v2.1b3.

**Comment by skiselkov** [comment]
Thanks for testing this, closing now.
