### ISSUE TITLE
Saves preferences to the disk root - XP11

### ISSUE THREAD

**Issue by FGremlin** [skiselkov/X-RAAS2#3]
Plugin doesn't save aircraft specific settings and creates X-RAAS.cfg in the disk root instead of X-Plane 11\Output\preferences\ directory. 
This problem occurs only on X-Plane 11.

[Log.txt](https://github.com/skiselkov/X-RAAS2/files/1260162/Log.txt)
[X-RAAS.cfg.txt](https://github.com/skiselkov/X-RAAS2/files/1260170/X-RAAS.cfg.txt)

**Comment by skiselkov** [comment]
I see you are running version 2.0.3. Can you please test with 2.1b2? There were changes to the way aircraft config saving is done there, so I first want to rule out any chance of a fix already being in X-RAAS.

**Comment by FGremlin** [comment]
Thanks! That fixed the issue! Thanks again for this great plugin :)

**Comment by skiselkov** [comment]
Glad you like it and that the latest beta fixes it. I'll be rolling out a final beta build & then release it.
